services:
  - type: web
    name: azure-stt-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_REGION
        value: centralindia
